"""Add obtained_marks and total_marks to exam_reports.

Revision ID: h4i5j6k7l8m9
Revises: g2c3d4e5f6a7
Create Date: 2026-04-14 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'h4i5j6k7l8m9'
down_revision = 'g2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_reports', sa.Column('obtained_marks', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('exam_reports', sa.Column('total_marks', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_reports', 'total_marks')
    op.drop_column('exam_reports', 'obtained_marks')
    # ### end Alembic commands ###
